services:
  redis:
    container_name: todo-redis
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - todo_network

  postgres:
    container_name: todo-db
    image: postgres:14.17
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo5082
    ports:
      - "5432:5432"
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge